# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define 'DHCP-1' do |node|
		node.vm.box = "ubuntu/bionic64" 
		node.vm.hostname = "EPUAKHAWO13DT100"
		node.vm.network "public_network"
		node.vm.network "private_network", ip: "172.16.2.100", netmask: "255.255.255.0", dns_nameserver: "127.0.0.1", dns_search: "EPAM.LOCAL",
			virtualbox__intnet: "internal_network"
		node.vm.synced_folder ".", "/vagrant"
		node.vm.provision "shell", path: "provisions/DHCP-1.sh"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "DHCP-1"
			vb.memory = 1024
			vb.cpus = 2
		end
	end
	config.vm.define 'DHCP-2' do |node|
		node.vm.box = "centos/7" 
		node.vm.hostname = "EPUAKHAWO13DT101"
		node.vm.network "public_network"
		node.vm.network "private_network", ip: "172.16.2.101", netmask: "255.255.255.0", dns_nameserver: "127.0.0.1", dns_search: "EPAM.LOCAL",
			virtualbox__intnet: "internal_network"
		node.vm.synced_folder ".", "/vagrant"
		node.vm.provision "shell", path: "provisions/DHCP-2.sh"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "DHCP-2"
			vb.memory = 1024
			vb.cpus = 2
		end
	end
	config.vm.define 'Client-3' do |node|
		node.vm.box = "centos/7" 
		node.vm.hostname = "EPUAKHAWO13DT18"
		node.vm.network "private_network", type: "dhcp", mac: "50465E6E8C18",
			virtualbox__intnet: "internal_network"
		node.vm.synced_folder ".", "/vagrant"
		node.vm.provision "shell", path: "provisions/Client-3.sh"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "Client-3"
			vb.memory = 512
			vb.cpus = 1
		end
	end
	config.vm.define 'Client-4' do |node|
		node.vm.box = "centos/7" 
		node.vm.hostname = "EPUAKHAWO13DT19"
		node.vm.network "private_network", type: "dhcp", mac: "50465E6E8C19",
			virtualbox__intnet: "internal_network"
		node.vm.synced_folder ".", "/vagrant"
		node.vm.provision "shell", path: "provisions/Client-4.sh"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "Client-4"
			vb.memory = 512
			vb.cpus = 1
		end
	end
	config.vm.define 'Client-5' do |node|
		node.vm.box = "ubuntu/bionic64" 
		node.vm.hostname = "EPUAKHAWO13DT20"
		node.vm.network "private_network", type: "dhcp", mac: "50465E6E8C20",
			virtualbox__intnet: "internal_network"
		node.vm.synced_folder ".", "/vagrant"
		node.vm.provision "shell", path: "provisions/Client-5.sh"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "Client-5"
			vb.memory = 512
			vb.cpus = 1
		end
	end
	config.vm.define 'Client-6' do |node|
		node.vm.box = "ubuntu/bionic64" 
		node.vm.hostname = "EPUAKHAWO13DT21"
		node.vm.network "private_network", type: "dhcp", mac: "50465E6E8C21",
			virtualbox__intnet: "internal_network"
		node.vm.synced_folder ".", "/vagrant"
		node.vm.provision "shell", path: "provisions/Client-6.sh"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "Client-6"
			vb.memory = 512
			vb.cpus = 1
		end
	end
	config.vm.define 'Client-7' do |node|
		node.vm.box = "centos/7" 
		node.vm.hostname = "EPUAKHAWO13DT22"
		node.vm.network "private_network", type: "dhcp", mac: "50465E6E8C22",
			virtualbox__intnet: "internal_network"
		node.vm.synced_folder ".", "/vagrant"
		node.vm.provision "shell", path: "provisions/Client-7.sh"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "Client-7"
			vb.memory = 512
			vb.cpus = 1
		end
	end
end
