# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define 'NAT' do |node|
		node.vm.box = "ubuntu/bionic64" 
		node.vm.hostname = "EPUAKHAWO13DT1"
		node.vm.network "public_network"
		node.vm.network "private_network", ip: "172.16.2.1", netmask: "255.255.255.192", dns_nameserver: "172.16.2.3", dns_search: "EPAM.LOCAL", 
			virtualbox__intnet: "internal_network_3"
		node.vm.synced_folder ".", "/vagrant"
		node.vm.provision "shell", path: "provisions/NAT.sh"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "NAT"
			vb.memory = 512
			vb.cpus = 2
		end
	end
	config.vm.define 'DHCP' do |node|
		node.vm.box = "ubuntu/bionic64" 
		node.vm.hostname = "EPUAKHAWO13DT2"
		node.vm.network "private_network", ip: "172.16.2.2", netmask: "255.255.255.192", dns_nameserver: "172.16.2.3", dns_search: "EPAM.LOCAL",
			virtualbox__intnet: "internal_network_3"
		node.vm.synced_folder ".", "/vagrant"
		node.vm.provision "shell", path: "provisions/DHCP.sh"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "DHCP"
			vb.memory = 512
			vb.cpus = 2
		end
	end
	config.vm.define 'DNS' do |node|
		node.vm.box = "ubuntu/bionic64" 
		node.vm.hostname = "EPUAKHAWO13DT3"
		node.vm.network "private_network", ip: "172.16.2.3", netmask: "255.255.255.192", dns_nameserver: "172.16.2.3", dns_search: "EPAM.LOCAL",
			virtualbox__intnet: "internal_network_3"
		node.vm.synced_folder ".", "/vagrant"
		node.vm.provision "shell", path: "provisions/DNS.sh"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "DNS"
			vb.memory = 512
			vb.cpus = 2
		end
	end		
end